# Generated by Django 3.0.5 on 2020-04-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='Ops',
            new_name='ops',
        ),
        migrations.RemoveField(
            model_name='op',
            name='body',
        ),
        migrations.AddField(
            model_name='draft',
            name='medium',
            field=models.TextField(default='-', max_length=30),
            preserve_default=False,
        ),
    ]
