# Generated by Django 3.0.5 on 2020-05-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_auto_20200407_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='version_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
