# Generated by Django 3.0.5 on 2020-05-01 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_draft_version_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='op',
            name='description',
            field=models.TextField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='op',
            name='medium',
            field=models.TextField(default='-', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draft',
            name='ops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='ops.Op'),
        ),
    ]
