# Generated by Django 3.0.5 on 2020-05-10 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0006_auto_20200510_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='ops',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='ops.Op'),
        ),
        migrations.AlterField(
            model_name='op',
            name='authors',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
