# Generated by Django 3.0.5 on 2020-05-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_auto_20200510_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='notes',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='body',
            field=models.TextField(default='-'),
        ),
    ]
