# Generated by Django 3.0.5 on 2020-05-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0008_auto_20200513_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='ops',
            new_name='op',
        ),
    ]
