# Generated by Django 3.0.5 on 2020-11-29 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0010_auto_20201129_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='draft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ops.Draft'),
        ),
    ]
