# Generated by Django 3.0.5 on 2020-11-29 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0011_auto_20201129_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='draft',
            new_name='drafts',
        ),
    ]
