# Generated by Django 3.0.5 on 2020-04-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='projects',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
