# Generated by Django 3.0.5 on 2020-05-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='projects',
        ),
    ]
